### ISSUE TITLE
Installing tree

### ISSUE THREAD

**Issue by Yulia88** [tocodeil/unix1-course-examples#100]
Hey,

I can't install the tree 
I receive the following error
Could not resolve 'il.archive.ubuntu.com' 
I tried to add fix-missing but still didn't work

**Comment by ynonp** [comment]
Sounds like a network issue. Is your machine connected to the internet?

Can you run `ping www.google.com` ? And what about `ping il.archive.ubuntu.com` ? and `dig www.google.com` ? And `dig il.archive.ubuntu.com` ?

**Comment by Yulia88** [comment]
Yes, I can run google, but not ping ubuntu 
dig gives me some output for both
And the machine is connected to network

**Comment by ynonp** [comment]
Sounds like your DNS provider is broken. Here's how to check and fix:

DNS is the mechanism that translates a name to a numeric IP address, for example it translates `il.archive.ubuntu.com` to `192.115.211.70`. If your DNS provider is broken your computer won't be able to translate the address and you'll the error you specified.

To test you can ping the server directly by IP address: `ping 192.115.211.70`. If it works you know you have a DNS problem.

To fix a DNS problem you'll want to define a different provider. There's a nice explanation (with pictures) here on how to change:
https://askubuntu.com/questions/2321/what-is-the-proper-way-to-change-the-dns-ip

You'll want to use `8.8.8.8` as your DNS provider address. This is a public DNS provider maintained by Google and it usually shows good results.

Let  me know if it works (or if not and we'll try a different route)

**Comment by Yulia88** [comment]
I don't have the same definitions as mentioned in the given URL + Im afraid to mess up with it

**Comment by ynonp** [comment]
רגע את לא עובדת על מכונה וירטואלית שהתקנת?
כי אם כן אין סיבה לחשוב. במקרה הגרוע מתקינים מחדש :)
(ובכל מקרה חלק בריא מתהליך למידה זה לשבור דברים. בשביל זה אני כאן ותמיד אפשר לתקן)

וגם- אולי תצרפי תמונות מסך של מה שאת רואה שונה ואנסה להכווין אותך לפי מה שאת רואה?

**Comment by ynonp** [comment]
אגב זו סידרת התמונות משינוי הגדרות אצלי על מכונת אובונטו 16.04 - אולי יעזור:

![virtualbox_mycoolbox_12_05_2017_20_15_51](https://cloud.githubusercontent.com/assets/128594/26009184/5d62cf3c-3750-11e7-9723-406cd6893085.png)
![virtualbox_mycoolbox_12_05_2017_20_16_27](https://cloud.githubusercontent.com/assets/128594/26009185/5d63f20e-3750-11e7-8598-dc7eaeafb181.png)
![virtualbox_mycoolbox_12_05_2017_20_16_37](https://cloud.githubusercontent.com/assets/128594/26009187/5d662114-3750-11e7-9474-9a1dfdcf56de.png)
![virtualbox_mycoolbox_12_05_2017_20_16_42](https://cloud.githubusercontent.com/assets/128594/26009183/5d62843c-3750-11e7-8c6f-b6ce52a2a4fc.png)
![virtualbox_mycoolbox_12_05_2017_20_16_55](https://cloud.githubusercontent.com/assets/128594/26009186/5d6553ba-3750-11e7-91ce-2b9f2ce80f1b.png)

אחרי ולפני השינוי את יכולה לראות דרך המסוף את שרת ה DNS 
שהמחשב שלך משתמש בו באמצעות הפקודה:

```
nmcli device show  | grep IP4.DNS
```

**Comment by Yulia88** [comment]
אני הורדתי את גרסת 17
אני לא מצליחה למצוא את מה שמודגם אצלך בתמונות 
אולי כי אני לא על 
WIFI?
אלא מחוברת ישירות לראוטר?
![1](https://cloud.githubusercontent.com/assets/28634107/26036303/bc2ed85a-38e3-11e7-8665-8b341ec5d55c.png)

**Comment by Yulia88** [comment]
שיניתי את ההגדרות שיתאימו כפי שמופיע בתמונות, התחלתי את המכונה הווירטואלית 
אך עדיין יש סירוב
![tree](https://cloud.githubusercontent.com/assets/28634107/26036350/a4464aec-38e4-11e7-8c6a-6ceb8bca020c.png)

**Comment by ynonp** [comment]
צריכה להוסיף sudo
לפני הפקודה:

```
sudo apt-get update
sudo apt-get install tree
```

**Comment by ynonp** [comment]
מה הפלט של:

```
nmcli device show  | grep IP4.DNS
```

ומה הפלט של:

```
dig il.archive.ubuntu.com
```

**Comment by Yulia88** [comment]
![tree](https://cloud.githubusercontent.com/assets/28634107/26286486/947defee-3e6f-11e7-9548-d720fa443178.JPG)

**Comment by ynonp** [comment]
totally a DNS problem but still not sure what. It looks like you're on the correct DNS server, but still not able to resolve il.archive.ubuntu.com

Two other ideas as a temporary solution:

1. In file `/etc/apt/sources.list` change all `il.archive.ubuntu.com` to `archive.ubuntu.com`. After that run `sudo apt-get update` and this will hopefully fix it.

2. If it doesn't, you can also try to add the following line to the file `/etc/hosts`:

```
192.115.211.70 il.archive.ubuntu.com
```

Let me know if any of the two work.

3. Also try to restart the virtual machine

4. And paste the output of `dig +trace il.archive.ubuntu.com` to get some more information

**Comment by Yulia88** [comment]
i don't have permission to change these files...
and here is the output

![capture](https://cloud.githubusercontent.com/assets/28634107/26313991/37ab4310-3f15-11e7-958c-48cf01618965.JPG)

**Comment by Yulia88** [comment]
I have downloaded the most updated version of Ubuntu, maybe I should download another one?

**Comment by ynonp** [comment]
You'll need to sudo in order to change the files. From terminal type `sudo -s`, then enter your password and then you'll be able to change them.

It's not related to the version of Ubuntu you downloaded, but to broken DNS configuration and the locale settings you selected during install (i.e. that you're in Israel).

**Comment by Yulia88** [comment]
First solution worked like magic! 
Thanks!

**Comment by ynonp** [comment]
I probably should have started there ... but we did learn some things about DNS which (hopefully) was also fun :)
