### ISSUE TITLE
סימן פלוס ("+")

### ISSUE THREAD

**Issue by Gadpal** [tocodeil/unix1-course-examples#103]
שלום ינון,

בתרגיל התאריך שנתת (סעיף 4), למעשה הדפסתי כ"string" פורמט מסוים של תאריך ושעה.

ביצירת ה"string" השתמשתי בסימן "+".

רציתי לדעת מה הסימן מייצג? מתי משתמשים בו? לאיזה פונקציות וכד'?

**Comment by ynonp** [comment]
הי גד,
סימן פלוס רלוונטי רק לפקודה 
date

יש לפעמים פקודות יוניקס שצריכות עוד סימן בנוסף למינוס הסטנדרטי ואז מתחילים להמציא. בעמוד התיעוד של כל פקודה אפשר לראות איזה יכולות יש לה, ובמקרה של date זה:
`man date`
