### ISSUE TITLE
תבניות

### ISSUE THREAD

**Issue by Gadpal** [tocodeil/unix1-course-examples#105]
אני חושש שאני מסתבך מעט עם עניין התבניות.
ניסיתי מספר ורסיות ורק אחת אבדה לי 
echo *["i","m","r","d"]? אני ממש לא בטוח שזו הנכונה, ואני לא מבין כל כך את ההיגיון מאחורי זה.
אשמח לפשט את העניין.

**Comment by ynonp** [comment]
על איזה שאלה?
