### ISSUE TITLE
שאלה מספר 4

### ISSUE THREAD

**Issue by roigizmo** [tocodeil/unix1-course-examples#113]
היי ינון,
משום מה אני מסתבך עם שאלה מספר 4 (שהיא אמורה לא להיות מסובכת בכלל).
כנראה שאני עושה משהו לא בסדר. 
זה מה שחשבתי לעשות: 

$ ln file 2 file 4
ואז אני אמור לעשות:
& ls -i file 2
&ls - i file 4
ולראות שלשניהם יש אותו מספר אינדקס

וזה לא יוצא לי
מה אני מפספס כאן?

**Comment by ynonp** [comment]
יש לך יותר מדי רווחים...

הפקודה צריכה היתה להיות
`ln file2 file4`

כלומר רווח אחד בין שני שמות הקבצים.

בשביל להכניס רווח באמצע שם קובץ, כלומר כדי לקרוא לקובץ
file 2
תצטרך להשתמש במרכאות סביב השם המלא באופן הבא:

`ln "file 2" "file 4"`

**Comment by roigizmo** [comment]
היי ינון,
זה מה שעשיתי וזה מה שהוא כתב:
failed to create hardlink : file exsits

איך זה הגיוני?

**Comment by ynonp** [comment]
נשמע שיש קובץ בשם file4
נסה להפעיל `ls` 
לראות איזה קבצים בתיקיה ואם כבר קיים הקישור למחוק

**Comment by roigizmo** [comment]
היי ינון,
אכן היה קובך כזה כבר
מחקתי אותו ועשיתי את הפקודה מחדש
וזה עובד.
תודה
