### ISSUE TITLE
נסיון לעלות קובץ תשבות 

### ISSUE THREAD

**Issue by moshikob99** [tocodeil/unix1-course-examples#115]
אני מנסה ללא הצלחה לעלות את קובץ התשובות לתרגיל 07_cmd_lab
ניסיתי להעלות שתי פורמטים של קבצים 
1- word
2- Notepad

**Comment by ynonp** [comment]
הי מושיקו
הקובץ צריך להיות בפורמט טקסט ושם הקובץ חייב להיות בדיוק כמו שמופיע בטאב ״הגשה״ וללא סיומת

**Comment by ynonp** [comment]
אם אתה מסתבך אפשר גם לשלוח אליי למייל

**Comment by moshikob99** [comment]
היי,
תודה רבה על העזרה, הצלחתי להעלות לאתר את התשובות.

בתאריך 28 במאי 2017 7:56 אחה״צ,‏ "ynonp" <notifications@github.com> כתב:

**Comment by ynonp** [comment]
👍
