### ISSUE TITLE
לגבי סוגי הקבצים

### ISSUE THREAD

**Issue by BENIDUDE** [tocodeil/unix1-course-examples#130]
b’ מייצגת block device, כלומר התקן חומרה שהכתיבה אליו מבוצעת בבלוקים. ביוניקס התקני חומרה מיוצגים על ידי קבצים על הדיסק.
‘c’ מייצגת character device כלומר התקן חומרה שהכתיבה אליו או הקריאה ממנו מבוצעת בתווים, לדוגמא התקן המקלדת או המסך.

לא בדיוק הבנתי את שני הסוגים האלו
הרצתי את הפקודה על תיקיה שיש לי שם תת תיקיה ואז אני מבין את מהות d אבל לא את האחרים

**Comment by ynonp** [comment]
הי,
בלינוקס דרייברים מיוצגים על ידי קבצים, וכך עבודה עם התקנים חיצוניים נראית כמו עבודה עם קבצים
למשל דרייבר של מדפסת, מסך, דיסק, וכן הלאה - לכולם יהיו קבצים מתאימים בתיקיית
`/dev`

האותיות b או c
ליד שם קובץ מציינות שהנתיב הזה מתיחס לדרייבר ולא לקובץ אמיתי

בנוסף, יש חלוקה לשני סוגים מרכזיים של דרייברים: אלו שעובדים תו-אחר-תו, למשל מקלדת, לעומת אלו שמעבירים בלוקים, למשל דיסק.
