### ISSUE TITLE
היי

### ISSUE THREAD

**Issue by moshikob99** [tocodeil/unix1-course-examples#134]
העליתי קובץ תשבות עם הרבה סימני שאלה ולא מושלם 
היה לי קשה יחסית התרגיל הזה והייתי שמח לקבל עזרה  לגבי כל סימני השאלה שלי.

**Comment by ynonp** [comment]
הי מושיקו,
הוספתי הערות והבהרות בגוף התרגיל. תעבור עליהם בבקשה תראה שעכשיו הכל ברור.

קישור להערות שלי:
https://github.com/tocodeil/unix1-course-examples/pull/133/files
עדכן כאן או במייל אם עדיין יש שאלות
תודה,
ינון
