### ISSUE TITLE
question 3,8  

### ISSUE THREAD

**Issue by BENIDUDE** [tocodeil/unix1-course-examples#142]
I was very close to an answer and would like to get you feed back on them
100%  It's very important for me to get 

 Another question do you forward a grade to Shay? 
I'm wondering because I need to know if it's OK to submit my home work as is or wait until I am sure it's I have no mistakes or questions for you?

**Comment by ynonp** [comment]
No grades. The goal is for you to learn and get feedback. Of course it's best to hand in as correct version as possible.
