### ISSUE TITLE
Fail to start Ubuntu from virtual box

### ISSUE THREAD

**Issue by LiatKotigaro** [tocodeil/unix1-course-examples#46]
When I'm trying to start Ubuntu from the virtual box, I get the error: This kernel requires an x86-64 CPU. Unable to boot - please use a kernel appropriate for your CPU. What should I do?

**Comment by ynonp** [comment]
Hi Liat,
Please install Ubuntu 32 bit:
http://mirror.isoc.org.il/pub/ubuntu-releases/16.04.1/ubuntu-16.04-desktop-i386.iso

**Comment by LiatKotigaro** [comment]
The issue was fixed.

Thanks,

Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>
