### ISSUE TITLE
Fail installing Ubuntu

### ISSUE THREAD

**Issue by LiatKotigaro** [tocodeil/unix1-course-examples#47]
When trying to install Ubuntu on virtual box, I get error that there is not enough disk space. The system needs 8.6GB to be installed and I have around 15GB free space. I don't know why I get this error. Do you have any clue?

**Comment by ynonp** [comment]
Hi Liat,
When creating your VM in VirtualBox interface you select the disk size the VM should get. Default value there is 8GB. I suspect you selected the default value there.

2 things to try:

1. Install a smaller ubuntu distro, such as the server edition:
http://mirror.isoc.org.il/pub/ubuntu-releases/16.04.1/ubuntu-16.04-server-i386.iso

2. Delete the VM you created and create a new one with more disk space

**Comment by LiatKotigaro** [comment]
Thanks it helped ☺

Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>

**Comment by LiatKotigaro** [comment]
I finally finished long installation of Ubuntu on the VirtualBox, but after restarting the system the installation window is displayed again. Can you tell me what am I doing wrong?

Thanks,


Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>

From: Kotigaro, Liat
Sent: Wednesday, December 28, 2016 11:04 AM
To: 'tocodeil/unix1-course-examples' <reply@reply.github.com>; tocodeil/unix1-course-examples <unix1-course-examples@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [tocodeil/unix1-course-examples] Fail installing Ubuntu (#47)

Thanks it helped ☺

Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>

**Comment by vitalipe** [comment]
I think you need to remove the image from the VM...

**Comment by LiatKotigaro** [comment]
And reinstall again?

Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>

**Comment by vitalipe** [comment]
no.. it's like having a disk-on-key or a CD inserted.. the system tries to boot form that device.. 
also you can just press Enter (I believe) and choose "boot from hard-disk".

also you can just boot to the live-cd and use it for the course.. it's fully functional linux system.. it's just unpacks everything to  ram... :)

**Comment by LiatKotigaro** [comment]
Thanks it worked.

Liat Kotigaro
R&D BE Core Server Engineer
Communication and Cyber Intelligence (CI)
Verint System Ltd.
Phone: (+972)- 9-9624960
E-mail: liat.kotigaro@verint.com<mailto:liat.kotigaro@verint.com>
Web: <www.verint.com<http://www.verint.com/>>
