### ISSUE TITLE
grep Line is of an even length

### ISSUE THREAD

**Issue by everybodyls** [tocodeil/unix1-course-examples#65]
לא מצאתי פתרון בעזרת grep - רוב הצעות להשתמש ב awk or sed

**Comment by vitalipe** [comment]
I agree with the internet :) grep is faster & simpler most of the time.. 
especially newer versions of grep.

``` awk "NR % 2" ```
but note that it also counts the "newline" char (\n)

I found the answer [here](https://www.math.utah.edu/docs/info/gawk_4.html). 
```NR``` - is a [builtin variable](https://www.math.utah.edu/docs/info/gawk_19.html#SEC184), the ```%``` sign means modulo division - the remainder of a division operation.
