### ISSUE TITLE
תרגיל הגשה FIND

### ISSUE THREAD

**Issue by maximus777666** [tocodeil/unix1-course-examples#71]
שלום,
רציתי לשאול לגבי שאילה 1 ו-2, האם הכוונה לתיקיות/קבצים ששייכים ליוזר שלך שאתה עובד כרגע? או כל הקבצים בתיקיית TMP
תודה,

**Comment by vitalipe** [comment]
Correct. In question 1 all the files that are owned by the current user, and question 2 all that are **not** owned by current user.

**hint:** everything is in the man page for ```find```
