### ISSUE TITLE
awk

### ISSUE THREAD

**Issue by everybodyls** [tocodeil/unix1-course-examples#73]
in last question you ask to splits this file into multiple file, 
one for each block

awk -F working on files
please explain how to recognize the block ?
what is the answer to this question

**Comment by ynonp** [comment]
Each block starts with a lowercase letter, so the following may be a good indication:

```
/^[a-z]/ { print "Block Start: $0" }
```

The other hint you need is awk can print a line to stdout (as presented) or append it to a file. The following awk script prints the first 5 lines from /etc/shells to a new file:

```
awk 'NR <= 10 { print > newfile.txt }'
```
