### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by irisfain** [tocodeil/unix1-course-examples#89]
I installed ubuntu-16.04-desktop-i386 on virtualBox 5.1.10
but was given only the option of ubuntu32 and not 64 
is it going to be a problem?

?is the iso file been used after the installation is finished or I can delete it

**Comment by ynonp** [comment]
Hi Iris,
Ubuntu 32 bit is fine for the course (it's the recommended option). You won't need the ISO after installation
