### ISSUE TITLE
מבנה תיקיות במערכת Linux

### ISSUE THREAD

**Issue by irisfain** [tocodeil/unix1-course-examples#95]
בטקסט המוצג מתחת רשום
dpks -L cowsay
האם זו טעות? אם לא, מה ההבדל בינו לבין 
dpkg -L cowsay

**Comment by ynonp** [comment]
טעות בטקסט. תיקנתי עכשיו הפקודה הנכונה היא
 dpkg -L cowsay

תודה על תשומת הלב!
